apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-php-nginx.fullname" . }}
  labels:
    {{- include "chart-php-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "chart-php-nginx.selectorLabels" . | nindent 4 }}
